spring:
  application:
    name: demo2
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    host1:
      host: localhost
      port: 5672
      virtual-host: host1
      username: admin
      password: 123456
    host2:
      host: localhost
      port: 5672
      virtual-host: host2
      username: admin
      password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  mail:
    host: smtp.yandex.com
    username: "test678912342" # 'test678912342' #@yandex.ru
    password: "muehzdqqwhwgvkwb" # 'test678912342.1'
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          writetimeout: 5000
          timeout: 5000
          port: 25
          auth: true
          starttls:
            debug: true
            enable: true
            required: true
    protocol: 'smtp'
    port: 25


server:
  port: 8081

logging:
  config: classpath:log4j2.yml



